# Generated by Django 4.1 on 2022-08-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('price', models.FloatField()),
                ('desc', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
