# Generated by Django 4.1 on 2022-08-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
