# Generated by Django 4.1 on 2022-08-06 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_name', models.CharField(max_length=50)),
                ('lesson_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'db_table': 'lesson_name',
            },
        ),
    ]
