# Generated by Django 4.1 on 2022-08-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_purchasecourse_delete_purchasedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
