# Generated by Django 4.1 on 2022-08-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasecourse',
            name='price',
            field=models.FloatField(),
        ),
    ]
