# Generated by Django 4.1 on 2022-08-08 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_purchasecourse_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecourse',
            name='purchase_course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasecourse',
            name='purchase_id',
            field=models.IntegerField(default=0),
        ),
    ]
