# Generated by Django 4.1 on 2022-08-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_purchasecourse_purchase_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasecourse',
            name='purchase_id',
            field=models.BooleanField(default=False),
        ),
    ]
