# Generated by Django 4.1 on 2022-08-08 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_purchasecourse_purchase_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasecourse',
            name='cust_id',
        ),
    ]
