# Generated by Django 4.1 on 2022-08-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_remove_purchasecourse_cust_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecourse',
            name='user_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasecourse',
            name='purchase_id',
            field=models.IntegerField(),
        ),
    ]
