# Generated by Django 4.1 on 2022-08-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mail_validate',
        ),
    ]
