# Generated by Django 4.1 on 2022-08-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_mail_validate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail_validate',
            field=models.IntegerField(default=0),
        ),
    ]
