# Generated by Django 4.1 on 2022-08-09 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_mail_validate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mail_validate',
        ),
    ]
